### ISSUE TITLE
Improve BF2 parsing with RegEx

### ISSUE THREAD

**Issue by TwitchPlaysBF2** [TwitchPlaysBF2/GameDataReader#2]
Look at parsing done in the `ParseValue()` method of `Settings` class, inside `GameDataReader.Battlefield2.Parsing`.

The parsing is done by just replacing all quotes. If a value contains quotes, they would get lost. 

This isn't problematic for playernames, since they don't allow quotes anyway (I think). But the prefix and other values could contain quotes. They would get lost.

**Comment by TwitchPlaysBF2** [comment]
Better to use `value.Trim('\"');`

**Comment by cetteup** [comment]
This can be closed, as refractor values are now already being parsed with regex.
